//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingCart.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<bool> IsCheckout { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
