//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingCart.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Order = new HashSet<Order>();
            this.Product = new HashSet<Product>();
            this.Sale = new HashSet<Sale>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> CreditCardID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual CreditCard CreditCard { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
